grafana:
  adminPassword: "admin"
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi


# Configure ServiceMonitor to scrape our app
additionalServiceMonitors:
  - name: learning-platform-monitor
    selector:
      matchLabels:
        app: learning-platform
    namespaceSelector:
      matchNames:
        - learning-platform
    endpoints:
      - port: http
        path: /metrics
        interval: 15s
