apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: learning-platform
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useWorkloadIdentity: "true"
    clientID: "50928a0a-13a9-4bea-9bcd-24f55d73eca5" # Client ID from ServiceAccount
    keyvaultName: "selfhostedvault"
    cloudName: ""
    tenantId: "784f7653-7880-43d4-8bc3-f77cbbf0e3ab"
    objects: |
      array:
        - |
          objectName: "session-secret"
          objectAlias: "SESSION_SECRET"
          objectType: secret
        - |
          objectName: "azure-sql-connection-string"
          objectAlias: "AZURE_SQL_CONNECTION_STRING"
          objectType: secret
        - |
          objectName: "azure-storage-connection-string"
          objectAlias: "AZURE_STORAGE_CONNECTION_STRING"
          objectType: secret
        - |
          objectName: "azure-storage-container"
          objectAlias: "AZURE_STORAGE_CONTAINER"
          objectType: secret
        - |
          objectName: "azure-storage-account-name"
          objectAlias: "AZURE_STORAGE_ACCOUNT_NAME"
          objectType: secret
