apiVersion: v1
kind: Service
metadata:
  name: learning-platform
  namespace: learning-platform
spec:
  selector:
    app: learning-platform
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP