apiVersion: v1
kind: ServiceAccount
metadata:
  name: learning-platform-sa
  namespace: learning-platform
  annotations:
    azure.workload.identity/client-id: "50928a0a-13a9-4bea-9bcd-24f55d73eca5"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: learning-platform-sa-binding
  namespace: learning-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: learning-platform-sa
  namespace: learning-platform
